fedora_task:
  container:
    image: fedora:latest
    cpu: 4
    memory: 2Gb
  install_script:
    - dnf update -y
    - dnf install -y cmake make gcc diffutils python-unversioned-command
                     SDL2-devel libpng-devel zlib-devel portaudio-devel
  script:
    - mkdir build
    - cd build
    - ../configure --enable-old-uae-cpu --enable-small-mem --disable-dsp
                  --enable-werror || { cat config.log; exit 1; }
    - make -j4
    - ctest -j4 || { cat Testing/Temporary/LastTest.log; exit 1; }

freebsd_task:
  freebsd_instance:
    image_family: freebsd-12-1
    cpu: 4
    memory: 4G
  install_script:
    - pkg update
    - pkg install -y pkgconf cmake gmake png devel/sdl20 devel/libedit
  script:
    - ./configure || { cat config.log; exit 1; }
    - gmake -j4
    - gmake test || { cat Testing/Temporary/LastTest.log; exit 1; }

macos_task:
  osx_instance:
    image: high-sierra-base
  install_script:
    - brew install cmake sdl2 libpng make tidy-html5
  script:
    - export PATH=/usr/local/bin:$PATH
    - ./configure --disable-osx-bundle || { cat config.log; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - gmake test || { cat Testing/Temporary/LastTest.log; exit 1; }
